name: Crawl Toutiao Hot News

on:
  schedule:
    - cron: '0 14 * * *'  # 每天UTC 14:00执行（北京时间晚上22:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
        
    - name: Run crawler
      run: |
        cd crawl
        python toutiao_crawler.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 检查news_data目录是否存在并且有文件
        if [ -d "crawl/news_data" ] && [ "$(ls -A crawl/news_data)" ]; then
          echo "Changes detected. Committing and pushing..."
          git add crawl/news_data/
          git commit -m "Update Toutiao hot news data"
          git push
        else
          echo "No changes or news_data directory is empty"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
