name: News Crawler Workflow

on:
  schedule:
    - cron: '0 14 * * *'  # 每天UTC 14:00执行（北京时间晚上22:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r crawl/requirements.txt
        
    - name: Run crawlers
      run: |
        cd crawl
        python toutiao_crawler.py
        python bing_crawler.py
        
    - name: Commit and push changes
      if: success()
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # 检查是否有文件变更
        if [ -n "$(git status --porcelain crawl/news_data)" ]; then
          git add crawl/news_data/
          git commit -m "Update news data [skip ci]"
          git push
        else
          echo "No changes detected"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
