name: Crawl Toutiao Hot News

on:
  schedule:
    - cron: '0 14 * * *'  # 每天UTC 14:00执行（北京时间晚上22:00）
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas
        
    - name: Run crawler
      run: |
        cd crawl
        python toutiao_crawler.py
        
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update Toutiao hot news data"
          git push
        fi    
